# Generated by Django 4.2.2 on 2025-09-01 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Eleicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('data_termino', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Eleitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Chapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('coordenador', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('qtd_votos', models.IntegerField()),
                ('eleita', models.BooleanField()),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapas', to='votacao.eleicao')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('chapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='votacao.chapa')),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='votacao.eleicao')),
                ('eleitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='votacao.eleitor')),
            ],
            options={
                'unique_together': {('eleitor', 'eleicao')},
            },
        ),
    ]
