# Generated by Django 4.2.2 on 2025-09-14 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voto',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='chapa',
            name='eleita',
        ),
        migrations.RemoveField(
            model_name='chapa',
            name='qtd_votos',
        ),
        migrations.AddField(
            model_name='eleicao',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('encerrada', 'Encerrada'), ('apurada', 'Apurada')], default='aberta', max_length=20),
        ),
        migrations.AddField(
            model_name='eleicao',
            name='vencedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleicoes_vencidas', to='votacao.chapa'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='matricula',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='eleitor',
            name='matricula',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='voto',
            constraint=models.UniqueConstraint(fields=('eleitor', 'eleicao'), name='unique_voto_por_eleicao'),
        ),
    ]
