# Generated by Django 4.2.2 on 2025-11-11 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votacao', '0002_alter_voto_unique_together_remove_chapa_eleita_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.AlterField(
            model_name='voto',
            name='chapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.chapa'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='eleicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.eleicao'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='eleitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Eleitor',
        ),
    ]
